phi:
  hf_key: "phi-1_5"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
  # ft_model_path: "locuslab/tofu_ft_phi-1.5"
wmdp-zephyr-7b-beta:
  hf_key: "wmdp-zephyr-7b-beta"
  question_start_tag: ""
  question_end_tag: ""
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
muse-news-llama2-7b:
  hf_key: "Llama-2-7b-hf"
  question_start_tag: ""
  question_end_tag: ""
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
muse-books-llama2-7b:
  hf_key: "Llama-2-7b-hf"
  question_start_tag: ""
  question_end_tag: ""
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
tofu-llama2-7b:
  hf_key: "Llama-2-7b-chat-hf"
  question_start_tag: "[inst] "
  question_end_tag: " [/inst]"
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
muse-llama2-7b:
  hf_key: "Llama-2-7b-chat-hf"
  question_start_tag: "[inst] "
  question_end_tag: " [/inst]"
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
tofu-llama3-8b:
  hf_key: "meta-llama/meta-llama-3-8b-instruct"
  question_start_tag: "<|start_header_id|>user<|end_header_id|>\n\n"
  question_end_tag: "<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
tofu-llama-3.1-8b:
  hf_key: "Llama-3.1-8B-Instruct"
  question_start_tag: "<|start_header_id|>user<|end_header_id|>\n\n"
  question_end_tag: "<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
  answer_tag: ""
  flash_attention2: "true"
  gradient_checkpointing: "true"
tofu-gemma-2-2b-it:
  hf_key: "gemma-2b"
  question_start_tag: "<start_of_turn>"
  question_end_tag: "<end_of_turn>"
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
kud-llama2-7b:
  hf_key: "meta-llama/llama-2-7b-chat-hf"
  question_start_tag: ""
  question_end_tag: ""
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
kud-llama3-8b:
  hf_key: "meta-llama/meta-llama-3-8b-instruct"
  question_start_tag: ""
  question_end_tag: ""
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
kud-gemma-2-2b-it:
  hf_key: "gemma-2b"
  question_start_tag: "<start_of_turn>"
  question_end_tag: "<end_of_turn>"
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
harry-gemma-2-2b-it:
  hf_key: "gemma-2b"
  question_start_tag: "<start_of_turn>"
  question_end_tag: "<end_of_turn>"
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
stablelm:
  hf_key: "stabilityai/stablelm-3b-4e1t"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
pythia-1.4:
  hf_key: "EleutherAI/pythia-1.4b-deduped"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"

